<?php
    class playerstats extends dbconnect
    {
        public function getPlayerStats() {
            if((!empty($_POST['playerstat_uid'])) && (is_numeric($_POST['playerstat_uid'])==true) && (isset($_POST['playerstat_btn']))) {
                $playerstat_uid = $_POST['playerstat_uid'];
                $_playerstat_uid = mysqli_real_escape_string($this->connect(), $playerstat_uid);
                // tabela
                // var_dump(is_numeric($playerstat_uid));
                echo "<div class='playerstats'>";
                    echo "<div>";
                        echo "<h2>Dane konta</h1>";
                    echo "</div>";
                    echo "<div class='stat'>";
                        echo "<p>UID: </p>";
                        echo "<p>002</p>";
                    echo "</div>";
                    echo "<div class='stat'>";
                        echo "<p>Nick: </p>";
                        echo "<p>002</p>";
                    echo "</div>";
                    echo "<div class='stat'>";
                        echo "<p>Premium: </p>";
                        echo "<p>002</p>";
                    echo "</div>";
                    echo "<div class='stat'>";
                        echo "<p>Przegrany czas(minuty): </p>";
                        echo "<p>002</p>";
                    echo "</div>";
                    echo "<div class='stat'>";
                        echo "<p>Data rejestracji: </p>";
                        echo "<p>002</p>";
                    echo "</div>";
                    echo "<div class='stat'>";
                        echo "<p>Ostatnio na serwerze: </p>";
                        echo "<p>002</p>";
                    echo "</div>";
                echo "</div>";

                echo "<div class='playerstats'>";
                    echo "<div>";
                        echo "<h2>Dane postaci</h1>";
                    echo "</div>";
                    echo "<div class='stat'>";
                        echo "<p>Skin: </p>";
                        echo "<p>002</p>";
                    echo "</div>";
                    echo "<div class='stat'>";
                        echo "<p>Rasa: </p>";
                        echo "<p>002</p>";
                    echo "</div>";
                    echo "<div class='stat'>";
                        echo "<p>Data urodzenia: </p>";
                        echo "<p>002</p>";
                    echo "</div>";
                    echo "<div class='stat'>";
                        echo "<p>HP: </p>";
                        echo "<p>002</p>";
                    echo "</div>";
                    echo "<div class='stat'>";
                        echo "<p>Gotówka przy sobie: </p>";
                        echo "<p>002</p>";
                    echo "</div>";
                    echo "<div class='stat'>";
                        echo "<p>Gotówka w banku: </p>";
                        echo "<p>002</p>";
                    echo "</div>";
                    echo "<div class='stat'>";
                        echo "<p>Siła: </p>";
                        echo "<p>002</p>";
                    echo "</div>";
                    echo "<div class='stat'>";
                        echo "<p>Kondycja: </p>";
                        echo "<p>002</p>";
                    echo "</div>";
                    echo "<div class='stat'>";
                        echo "<p>Głód: </p>";
                        echo "<p>002</p>";
                    echo "</div>";
                    echo "<div class='stat'>";
                        echo "<p>Umiejętności grafiti: </p>";
                        echo "<p>002</p>";
                    echo "</div>";
                    echo "<div class='stat'>";
                        echo "<p>Prawa jazdy: </p>";
                        echo "<p>002</p>";
                    echo "</div>";
                    echo "<div class='stat'>";
                        echo "<p>Opis postaci: </p>";
                        echo "<p>002</p>";
                    echo "</div>";
                echo "</div>";

                echo "<div class='playerstats'>";
                    echo "<div>";
                        echo "<h2>Kary</h1>";
                    echo "</div>";
                    echo "<div class='stat'>";
                        echo "<p>Blokada OOC: </p>";
                        echo "<p>002</p>";
                    echo "</div>";
                    echo "<div class='stat'>";
                        echo "<p>Blokada bicia: </p>";
                        echo "<p>002</p>";
                    echo "</div>";
                    echo "<div class='stat'>";
                        echo "<p>Blokada PW: </p>";
                        echo "<p>002</p>";
                    echo "</div>";
                    echo "<div class='stat'>";
                        echo "<p>Więzienie: </p>";
                        echo "<p>002</p>";
                    echo "</div>";
                echo "</div>";

                echo "<table>";
                    echo "<tr>";
                        echo "<th>ID</th>";
                        echo "<th>Frakcja</th>";
                        echo "<th>Ranga</th>";
                        echo "<th>Staż obecnie</th>";
                        echo "<th>Staż łącznie</th>";
                    echo "</tr>";
                    echo "<tr>";
                        echo "<td>1</td>";
                        echo "<td>1</td>";
                        echo "<td>1</td>";
                        echo "<td>1</td>";
                        echo "<td>1</td>";
                    echo "</tr>";
                echo "</table>";

                echo "<table>";
                    echo "<tr>";
                        echo "<th>ID</th>";
                        echo "<th>Nazwa organizacji</th>";
                        echo "<th>Ranga</th>";
                    echo "</tr>";
                    echo "<tr>";
                        echo "<td>1</td>";
                        echo "<td>1</td>";
                        echo "<td>1</td>";
                    echo "</tr>";
                echo "</table>";

                echo "<table>";
                    echo "<tr>";
                        echo "<th>ID</th>";
                        echo "<th>Nazwa domu</th>";
                        echo "<th>Opłacony do</th>";
                    echo "</tr>";
                    echo "<tr>";
                        echo "<td>1</td>";
                        echo "<td>1</td>";
                        echo "<td>1</td>";
                    echo "</tr>";
                echo "</table>";

                echo "<table>";
                    echo "<tr>";
                        echo "<th>ID</th>";
                        echo "<th>Nazwa budynku</th>";
                        echo "<th>Opłacony do</th>";
                    echo "</tr>";
                    echo "<tr>";
                        echo "<td>1</td>";
                        echo "<td>1</td>";
                        echo "<td>1</td>";
                    echo "</tr>";
                echo "</table>";

                echo "<table>";
                    echo "<tr>";
                        echo "<th>ID</th>";
                        echo "<th>Nazwa pojazdu</th>";
                        echo "<th>Przebieg</th>";
                        echo "<th>Przechowalnia</th>";
                    echo "</tr>";
                    echo "<tr>";
                        echo "<td>1</td>";
                        echo "<td>1</td>";
                        echo "<td>1</td>";
                        echo "<td>1</td>";
                    echo "</tr>";
                echo "</table>";
            } else
                echo "<div class='nodata'>Brak danych do wyświetlenia</div>";
        }
    }
?>